// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbbnzimcvtfwjcmltdeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiYm56aW1jdnRmd2pjbWx0ZGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDM0NDEsImV4cCI6MjA2OTYxOTQ0MX0.BqZluhmBAzA46GCFqM3dfeC-Bc8xlsEb35fm7bK0toI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});